Javascript modal -Daniel Cho
danielycho/c1022-code-solutions pull request #45
Opened 2022-10-25 23:34 UTC by danielycho

![modal-1](https://user-images.githubusercontent.com/112663686/197901299-4d5d4bbc-088e-42a5-a0f4-ac75cdfc18c2.jpg)
![modal-2](https://user-images.githubusercontent.com/112663686/197901306-3939a4f0-cbcb-43ea-8405-df83cf699178.jpg)

2022-10-25 23:37 UTC, codingcodymiller requested changes

2022-10-25 23:37 UTC, codingcodymiller commented on javascript-modal/main.js
> +function overLayAndNoAppear(event) {
How about `showModal`?

2022-10-25 23:37 UTC, codingcodymiller commented on javascript-modal/main.js
> +function clickNoForNoOverlay(event) {
How about `hideModal`?

2022-10-25 23:40 UTC, danielycho commented
![image](https://user-images.githubusercontent.com/112663686/197901890-5aa1394b-38c6-4905-b86b-cdaf1345c1f2.png)

2022-10-27 15:56 UTC, codingcodymiller approved these changes

2022-10-27 16:00 UTC, merged